### ISSUE TITLE
extensions in fragment shader code throw error message

### ISSUE THREAD

**Issue by Quasimondo** [spite/ShaderEditorExtension#13]
If there is an #extension statement in a shader (like for example in Three.js when normal maps are used in a material) an error line "extension is not supported" is inserted into the shader code and it cannot be compiled. The issue here is that the shader runs just fine so that error message seems to be incorrect or based on the configuration of the editor.

You can test it with this demo - Program #3 is a shader that uses the derivatives and has the line 
 `#extension GL_OES_standard_derivatives : enable`
in it: http://threejs.org/examples/webgl_materials_normalmap.html

**Comment by spite** [comment]
Good catch! 

I added support for extensions, but with the rewrite, I forgot to add it back. 

Fixed here https://github.com/spite/ShaderEditorExtension/commit/818d69166d9e6e6ad6c50562840f335880488743, I'll update the extension and chrome will auto-update it.

**Comment by spite** [comment]
Updated on [1.0.8](https://chrome.google.com/webstore/detail/shader-editor/ggeaidddejpbakgafapihjbgdlbbbpob)
