### ISSUE TITLE
Find-on-page (on shaders) raise error

### ISSUE THREAD

**Issue by ebraminio** [spite/ShaderEditorExtension#14]
When I press Ctrl+F on a shader editor to search a text, from inspector's inspector console I see an error, apparently `CodeMirror.connect` is missed and some module of codemirror is not included here to do the functionality.

**Comment by spite** [comment]
Should be fixed with https://github.com/spite/ShaderEditorExtension/commit/7fd75c206fed04b2fbea5c8d61df6ada6244b92e. It will be deployed with v1.0.16
