### ISSUE TITLE
Shaders don't display correctly after page reload

### ISSUE THREAD

**Issue by kenrussell** [spite/ShaderEditorExtension#7]
To reproduce:
1. Open https://www.khronos.org/registry/webgl/sdk/demos/google/san-angeles/
2. Open the Developer Tools and the Shader Editor; reload the page
3. Note that the three programs have different sources
4. Reload the page

Expected:
The programs' sources continue to display correctly.

Actual:
All three programs seem to have the same sources.

**Comment by kenrussell** [comment]
Forgot the browser version: 44.0.2359.0 (Official Build) canary (64-bit) on a Retina Display MacBook Pro, OS X 10.9.5.

**Comment by snovak** [comment]
This seems to be specific to libGDX applications exported with GWT. 

http://libgdx.badlogicgames.com/demos/invaders/

more libGDX examples all have the same result from: http://libgdx.badlogicgames.com/demos

`Uncaught java.lang.RuntimeException: com.google.gwt.core.client.JavaScriptException: (TypeError) 
 __gwt$exception: <skipped>: Cannot read property '__uuid' of null(anonymous function) @ EB4441EB6DCDBB6CB2C54A710F25C97B.cache.html:6393`

I still see the shader programs on the page though.  So, that's cool!  But, the app won't keep running. 

Recreate with steps 1 and 2 above.

**Comment by spite** [comment]
Should be corrected in v1.0.13 https://github.com/spite/ShaderEditorExtension/issues/1

**Comment by snovak** [comment]
I thought I'd come and get an update on this.  I think you did it!  Seems to be working in the demos for libGDX now!

**Comment by spite** [comment]
Excellent! Glad to hear it's working, thanks for the update :)
